### ISSUE TITLE
Problem with the actions tab

### ISSUE THREAD

**Issue by MateusKH** [RedWirePlatinumTwo/RedWiresMinecraftMod#1] opened 2024-04-14 15:31 UTC
hear a small problem in the actions tab.
![Captura de tela 2024-04-14 122957](https://github.com/RedWirePlatinumTwo/RedWiresMinecraftMod/assets/136277849/fcf12079-2c9f-489b-97c2-705216706639)

**Comment by RedWirePlatinumTwo** [comment] 2024-04-14 15:38
what version is this?

**Comment by MateusKH** [comment] 2024-04-14 16:53
the latest, 1.1.2

**Comment by RedWirePlatinumTwo** [comment] 2024-04-14 17:24
Weird, I'm not having any issues after downloading my own plugin from the site. Can you post your mcreator.log file?

**Comment by MateusKH** [comment] 2024-04-15 15:39
[mcreator_2024_04_14-30.log](https://github.com/RedWirePlatinumTwo/RedWiresMinecraftMod/files/14981254/mcreator_2024_04_14-30.log)

**Comment by RedWirePlatinumTwo** [comment] 2024-04-16 17:22
I mean the one named _specifically_ mcreator.log, since that logs when mcreator loads (other mcreator log files gives logs when in-game)

**Comment by MateusKH** [comment] 2024-04-16 21:45
and where is that?

**Comment by RedWirePlatinumTwo** [comment] 2024-04-16 22:23
if you're on windows its C:\Users\YOURUSER\.mcreator\logs

**Comment by MateusKH** [comment] 2024-04-17 02:40
[mcreator_2024_04_16-4.log](https://github.com/RedWirePlatinumTwo/RedWiresMinecraftMod/files/15004832/mcreator_2024_04_16-4.log)
[mcreator_2024_04_16-5.log](https://github.com/RedWirePlatinumTwo/RedWiresMinecraftMod/files/15004837/mcreator_2024_04_16-5.log)
[mcreator_2024_04_16-6.log](https://github.com/RedWirePlatinumTwo/RedWiresMinecraftMod/files/15004838/mcreator_2024_04_16-6.log)
[mcreator_2024_04_16-7.log](https://github.com/RedWirePlatinumTwo/RedWiresMinecraftMod/files/15004839/mcreator_2024_04_16-7.log)
[mcreator_2024_04_16-8.log](https://github.com/RedWirePlatinumTwo/RedWiresMinecraftMod/files/15004840/mcreator_2024_04_16-8.log)
[mcreator_2024_04_16-9.log](https://github.com/RedWirePlatinumTwo/RedWiresMinecraftMod/files/15004841/mcreator_2024_04_16-9.log)
[mcreator_2024_04_16-10.log](https://github.com/RedWirePlatinumTwo/RedWiresMinecraftMod/files/15004842/mcreator_2024_04_16-10.log)
[mcreator_2024_04_16-11.log](https://github.com/RedWirePlatinumTwo/RedWiresMinecraftMod/files/15004843/mcreator_2024_04_16-11.log)

**Comment by RedWirePlatinumTwo** [comment] 2024-04-17 02:50
..is there not a file **exactly** named "mcreator.log"? It should be there

**Comment by MateusKH** [comment] 2024-04-17 02:53
[mcreator.log](https://github.com/RedWirePlatinumTwo/RedWiresMinecraftMod/files/15004907/mcreator.log)

this one?

**Comment by RedWirePlatinumTwo** [comment] 2024-04-17 02:54
Yep, thanks

**Comment by RedWirePlatinumTwo** [comment] 2024-04-19 04:09
I believe I've finally resolved the issue, try downloading 1.2.0 to see if it was fixed

**Comment by MateusKH** [comment] 2024-04-19 15:48
Hi, it looks like it hasn't been resolved. Still remain
![image](https://github.com/RedWirePlatinumTwo/RedWiresMinecraftMod/assets/136277849/991282ae-82c1-4ae5-9f43-f6bb2b399cd7)

**Comment by MateusKH** [comment] 2024-04-19 15:51
I've seen this error in other plugins, it's something wrong with the translation, whether in the "lang/ texts" file

**Comment by MateusKH** [comment] 2024-04-19 15:52
it is completely unusable, unless you research blockly.

**Comment by MateusKH** [comment] 2024-04-19 16:10
[mcreator.log](https://github.com/RedWirePlatinumTwo/RedWiresMinecraftMod/files/15042925/mcreator.log)

**Comment by LFDPhoenix1411** [comment] 2024-04-19 20:22
The problem is still there with version '1.2.2'

Every time you open the ACTION tab, it throws an :

`2024-04-19-22:19:17 [JavaFX Application Thread/INFO] [Launcher] [JFX JS bridge] [undefined: 651] TypeError: Invalid block definition for type: string_iterator`

[mcreator.log](https://github.com/RedWirePlatinumTwo/RedWiresMinecraftMod/files/15045347/mcreator.log)

**Comment by RedWirePlatinumTwo** [comment] 2024-04-19 20:23
> I've seen this error in other plugins, it's something wrong with the translation, whether in the "lang/ texts" file

It can't be that, just changed my language to brazil and re-loaded mcreator and im still not having the issue

**Comment by RedWirePlatinumTwo** [comment] 2024-04-19 20:24
this issue is so annoying oh my godddd 😔

**Comment by LFDPhoenix1411** [comment] 2024-04-19 20:32
> The problem is still there with version '1.2.2'
> 
> Every time you open the ACTION tab, it throws an :
> 
> `2024-04-19-22:19:17 [JavaFX Application Thread/INFO] [Launcher] [JFX JS bridge] [undefined: 651] TypeError: Invalid block definition for type: string_iterator`
> 
> [mcreator.log](https://github.com/RedWirePlatinumTwo/RedWiresMinecraftMod/files/15045347/mcreator.log)

I think the issue is in this path of the plugin
`/procedures/text_split_foreach.json` Line `36`
because that's the only time you find type the type `string_iterator` and the error is about an Invalid block definition for type: `string_iterator`

**Comment by MateusKH** [comment] 2024-04-19 20:47
There is only one way to solve this, the quickest way is to remove the problem blockly.

**Comment by LFDPhoenix1411** [comment] 2024-04-19 21:05
> > I've seen this error in other plugins, it's something wrong with the translation, whether in the "lang/ texts" file
> 
> It can't be that, just changed my language to brazil and re-loaded mcreator and im still not having the issue

do you have the file-manager plugin installed?
if so this one fixes for some reason the issues

**Comment by RedWirePlatinumTwo** [comment] 2024-04-19 22:00
Yeah I do, maybe I just gotta rename the string iterator procedure?? I dunno, I'll try it when I get back home

**Comment by LFDPhoenix1411** [comment] 2024-04-19 23:14
> Yeah I do, maybe I just gotta rename the string iterator procedure?? I dunno, I'll try it when I get back home

Possible but IDK (I don't do plugins) when I renamed it my MCreator didn't launch anymore, but maybe I did something wrong

**Comment by RedWirePlatinumTwo** [comment] 2024-04-19 23:22
well you have to rename *everything*, the one in the first procedure folders, the one in both generator folders, and replace "string_iterator" in text_split_foreach to whatever u renamed it to

**Comment by RedWirePlatinumTwo** [comment] 2024-04-20 21:58
Before I re-name the string iterator files, I want to test something out that nerdypuzzle suggested first. Does this fix the issue for you?
[redwiresplugin.zip](https://github.com/RedWirePlatinumTwo/RedWiresMinecraftMod/files/15049852/redwiresplugin.zip)

**Comment by LFDPhoenix1411** [comment] 2024-04-20 22:17
wait i test it

**Comment by LFDPhoenix1411** [comment] 2024-04-20 22:22
![javaw_n0O4XqEhBz](https://github.com/RedWirePlatinumTwo/RedWiresMinecraftMod/assets/95172621/bff57d8d-d08b-4430-bf6e-71c728180914)

still dosent work

the error is still
`2024-04-21-00:21:26 [JavaFX Application Thread/INFO] [Launcher] [JFX JS bridge] [undefined: 651] TypeError: Invalid block definition for type: string_iterator`

[mcreator.log](https://github.com/RedWirePlatinumTwo/RedWiresMinecraftMod/files/15049920/mcreator.log)

**Comment by RedWirePlatinumTwo** [comment] 2024-04-21 00:50
Okay so it took me too long to figure out most likely why this issue is occuring, so *hopefully* this works
[redwiresplugin.zip](https://github.com/RedWirePlatinumTwo/RedWiresMinecraftMod/files/15050265/redwiresplugin.zip)

**Comment by RedWirePlatinumTwo** [comment] 2024-04-21 02:58
Actions tab is officially fixed as of v1.2.3

**Closed** 2024-04-21 02:57 UTC
